### ISSUE TITLE
Auth problem "invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by aukfood** [YPSI-SAS/centctl#20]
**Describe the bug**
Hello YPSI Teams, happy new year :)

I have a bug with cenctl when I try to connect : 
```
~/scripts/centctl$ ./centctl --insecure --url "https://myurl" --login "login" --password "password" list host
[ERROR] 2023/01/05 06:09:36 centctl/cmd.initConfig:root.go:213 centctl authentification - invalid character '<' looking for beginning of value
```

Same problem with yaml file for configuration : 
```
servers:
  - server: "centreon"
    url: "https://myrul"
    insecure: true
    login: "mylogin"
    password: "mypassword"
    version: "v2"
    default: true
```

**Versions**
* centctl : 2.5.5
* centreon : 21.10.9
* linux : Linux Mint 21

Best regards
